workflows:
  android-release:
    name: Microscópio USB - Build Android
    max_build_duration: 60

    instance_type: mac_mini_m2

    environment:
      flutter: stable

      vars:
        PACKAGE_NAME: "com.microscopiousb"

    scripts:
      - name: Verificar Flutter
        script: |
          flutter --version

      - name: Instalar dependências
        script: |
          flutter pub get

      - name: Build APK Release
        script: |
          flutter build apk --release --split-per-abi

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/**/mapping.txt

    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
        notify:
          success: true
          failure: true
