name: microscopio_usb_visual
publish_to: 'none'
version: 1.0.0+visual

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/microscopio_hero.png
