import 'package:flutter/material.dart';

void main() => runApp(const MicroscopioVisualApp());

class MicroscopioVisualApp extends StatelessWidget {
  const MicroscopioVisualApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'Microscópio USB — Visual',
    theme: ThemeData.dark(useMaterial3: true).copyWith(
      scaffoldBackgroundColor: const Color(0xFF04070F),
      colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF7B2FF7), brightness: Brightness.dark),
    ),
    home: const WelcomeScreen(),
  );
}

class WelcomeScreen extends StatefulWidget {
  const WelcomeScreen({super.key});
  @override State<WelcomeScreen> createState() => _WelcomeScreenState();
}
class _WelcomeScreenState extends State<WelcomeScreen> {
  bool onboarding = false;
  void enter() => Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const MainScreen()));
  @override Widget build(BuildContext context) => Scaffold(
    body: Stack(children: [
      const Positioned.fill(child: DecoratedBox(decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment.topLeft,end: Alignment.bottomRight,colors:[Color(0xFF060B18),Color(0xFF0B1530),Color(0xFF071022)])))),
      Positioned(top:-90,right:-70,child: _glow(const Color(0xFF7B2FF7),240)),
      Positioned(bottom:-100,left:-80,child: _glow(const Color(0xFF00D4FF),280)),
      SafeArea(child: Padding(padding: const EdgeInsets.all(20), child: Column(children:[
        Row(crossAxisAlignment: CrossAxisAlignment.start, children:[Expanded(child:_status()),const SizedBox(width:12),const _Clock(),const SizedBox(width:12),_shortcuts(enter)]),
        const SizedBox(height:24),
        Expanded(child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth:760),child:_hero()))),
        const SizedBox(height:18),
        FilledButton.icon(onPressed:()=>setState(()=>onboarding=true),icon:const Icon(Icons.play_arrow_rounded),label:const Padding(padding:EdgeInsets.symmetric(horizontal:12,vertical:13),child:Text('Primeiros passos',style:TextStyle(fontWeight:FontWeight.w700)))),
        const SizedBox(height:18),
        const Row(children:[Expanded(child:_Feature(icon:Icons.zoom_in,title:'Amplie',text:'Controle e observe')),SizedBox(width:10),Expanded(child:_Feature(icon:Icons.explore,title:'Explore',text:'Ferramentas na tela')),SizedBox(width:10),Expanded(child:_Feature(icon:Icons.auto_awesome,title:'Descubra',text:'Recursos inteligentes'))]),
      ]))),
      if(onboarding) _Onboarding(onClose:()=>setState(()=>onboarding=false),onEnter:enter),
    ]));
}
Widget _glow(Color c,double s)=>Container(width:s,height:s,decoration:BoxDecoration(shape:BoxShape.circle,gradient:RadialGradient(colors:[c.withValues(alpha:.3),c.withValues(alpha:0)])));
Widget _status()=>Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:10),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.05),borderRadius:BorderRadius.circular(30),border:Border.all(color:const Color(0xFF7B2FF7).withValues(alpha:.5))),child:const Row(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.circle,size:10,color:Color(0xFF34D399)),SizedBox(width:10),Flexible(child:Text('Câmera USB detectada com sucesso',overflow:TextOverflow.ellipsis)),SizedBox(width:8),Icon(Icons.check_circle,color:Color(0xFF34D399),size:18)]));
class _Clock extends StatelessWidget { const _Clock(); @override Widget build(BuildContext c){final n=DateTime.now();return Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Text('${n.hour.toString().padLeft(2,'0')}:${n.minute.toString().padLeft(2,'0')}',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w700)),Text('${n.day.toString().padLeft(2,'0')}/${n.month.toString().padLeft(2,'0')}',style:const TextStyle(color:Colors.white70))]);}}
Widget _shortcuts(VoidCallback go)=>Column(children:[_Shortcut(Icons.usb,'USB',const Color(0xFF7B2FF7),go),const SizedBox(height:8),_Shortcut(Icons.settings,'Config.',const Color(0xFF2F80FF),go),const SizedBox(height:8),_Shortcut(Icons.photo_library,'Galeria',const Color(0xFF12C6A0),go)]);
class _Shortcut extends StatelessWidget{final IconData icon;final String label;final Color color;final VoidCallback onTap;const _Shortcut(this.icon,this.label,this.color,this.onTap);@override Widget build(BuildContext c)=>InkWell(onTap:onTap,borderRadius:BorderRadius.circular(12),child:Column(children:[Container(width:40,height:40,decoration:BoxDecoration(color:color.withValues(alpha:.14),shape:BoxShape.circle,border:Border.all(color:color.withValues(alpha:.5))),child:Icon(icon,color:color,size:18)),Text(label,style:const TextStyle(fontSize:9,color:Colors.white60))]));}
Widget _hero()=>Container(height:330,decoration:BoxDecoration(borderRadius:BorderRadius.circular(28),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.45),blurRadius:30)],image:const DecorationImage(image:AssetImage('assets/images/microscopio_hero.png'),fit:BoxFit.cover)),child:Container(decoration:BoxDecoration(borderRadius:BorderRadius.circular(28),gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.transparent,Colors.black.withValues(alpha:.55)])),child:const Center(child:CircleAvatar(radius:34,backgroundColor:Colors.black54,child:Icon(Icons.play_arrow_rounded,size:40)))));
class _Feature extends StatelessWidget{final IconData icon;final String title,text;const _Feature({required this.icon,required this.title,required this.text});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.045),borderRadius:BorderRadius.circular(16),border:Border.all(color:Colors.white12)),child:Row(children:[Icon(icon,color:Colors.white70,size:20),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),Text(text,style:const TextStyle(color:Colors.white54,fontSize:11))]))]));}
class _Onboarding extends StatelessWidget{final VoidCallback onClose,onEnter;const _Onboarding({required this.onClose,required this.onEnter});@override Widget build(BuildContext c)=>Container(color:const Color(0xF2080C18),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:520),child:Card(color:const Color(0xFF111827),child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.biotech_rounded,size:60,color:Color(0xFF7B2FF7)),const SizedBox(height:16),const Text('Conheça o Microscópio USB',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800),textAlign:TextAlign.center),const SizedBox(height:10),const Text('Esta é uma prévia visual. Todos os botões abaixo são navegáveis, mas hardware, câmera e IA estão desativados nesta versão.',textAlign:TextAlign.center,style:TextStyle(color:Colors.white70)),const SizedBox(height:24),FilledButton(onPressed:onEnter,child:const Text('Entrar no app')),TextButton(onPressed:onClose,child:const Text('Fechar'))]))))));}

class MainScreen extends StatefulWidget{const MainScreen({super.key});@override State<MainScreen> createState()=>_MainScreenState();}
class _MainScreenState extends State<MainScreen>{bool grid=false;bool recording=false;bool light=false;bool compare=false;bool tool=false;String mode='NORMAL';
void nav(Widget w)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>w));
@override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.black,body:Stack(children:[
  Positioned.fill(child:Container(decoration:const BoxDecoration(gradient:RadialGradient(center:Alignment.center,radius:1.2,colors:[Color(0xFF26324A),Color(0xFF0A0D14),Colors.black])))),
  Positioned.fill(child:CustomPaint(painter:_MicroscopePainter(grid:grid,compare:compare))),
  if(grid) Positioned.fill(child:CustomPaint(painter:_GridPainter())),
  Positioned(top:16,left:16,child:_round(Icons.circle,color:Colors.green,onTap:()=>_snack('Câmera conectada (simulação)'))),
  Positioned(left:14,top:0,bottom:0,child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[_round(Icons.camera_alt,onTap:()=>_snack('Captura simulada')),_gap(),_round(recording?Icons.stop:Icons.videocam,active:recording,onTap:()=>setState(()=>recording=!recording)),_gap(),_round(Icons.straighten,onTap:()=>_snack('Medição simulada')),_gap(),_round(Icons.zoom_in,onTap:()=>_snack('Zoom visual')),_gap(),_round(Icons.refresh,onTap:()=>_snack('Reconexão simulada')),_gap(),_round(Icons.eject,onTap:()=>_snack('Desconectar (simulação)')),_gap(),_round(grid?Icons.grid_on:Icons.grid_off,active:grid,onTap:()=>setState(()=>grid=!grid)),])),
  Positioned(right:14,top:16,bottom:16,child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[_round(Icons.help_outline,onTap:()=>_snack('Ajuda')), _gap(),_round(Icons.photo_library,onTap:()=>nav(const GalleryScreen())),_gap(),_round(Icons.lightbulb_outline,active:light,onTap:()=>setState(()=>light=!light)),_gap(),_round(Icons.palette,onTap:()=>_snack('Efeitos visuais')),_gap(),_round(Icons.checklist_outlined,onTap:()=>nav(const NotesScreen())),_gap(),_round(Icons.settings,onTap:()=>nav(const ControlsScreen())),])),
  Positioned(top:16,left:0,right:0,child:Center(child:Row(mainAxisSize:MainAxisSize.min,children:[_round(Icons.rotate_left,onTap:()=>_snack('Girar')), _gap(s:8),_round(Icons.rotate_right,onTap:()=>_snack('Girar')), _gap(s:8),_round(Icons.flip,onTap:()=>_snack('Espelhar')), _gap(s:8),_round(Icons.swap_vert,onTap:()=>_snack('Espelhar')), _gap(s:8),Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:9),decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(20)),child:Text(mode,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700))), _gap(s:8),_round(Icons.auto_awesome,onTap:()=>_snack('IA desativada na prévia'))])),
  Positioned(bottom:72,left:0,right:0,child:Center(child:Row(mainAxisSize:MainAxisSize.min,children:[_round(Icons.vertical_split,active:compare,onTap:()=>setState(()=>compare=!compare)),_gap(s:8),_round(Icons.timelapse,onTap:()=>_snack('Time-lapse visual')),_gap(s:8),_round(Icons.document_scanner,onTap:()=>_snack('Digitalização visual'))])),
  Positioned(bottom:20,left:0,right:0,child:Center(child:Row(mainAxisSize:MainAxisSize.min,children:[_round(Icons.title,onTap:()=>_snack('Texto')), _gap(s:8),_round(Icons.edit,active:tool,onTap:()=>setState(()=>tool=!tool)),_gap(s:8),_round(Icons.delete_outline,onTap:()=>_snack('Limpar anotações')),_gap(s:8),_round(Icons.brightness_6,onTap:()=>_snack('Brilho'))])),
  Positioned(bottom:16,left:16,child:Text('PRÉVIA VISUAL • HARDWARE DESATIVADO',style:TextStyle(color:Colors.white.withValues(alpha:.5),fontSize:10,letterSpacing:1.1))),
]));
Widget _round(IconData i,{VoidCallback? onTap,bool active=false,Color? color})=>InkWell(onTap:onTap,borderRadius:BorderRadius.circular(22),child:Container(width:42,height:42,decoration:BoxDecoration(color:active?const Color(0xFF7B2FF7).withValues(alpha:.85):Colors.black54,shape:BoxShape.circle,border:Border.all(color:Colors.white12)),child:Icon(i,color:color??Colors.white,size:19))); Widget _gap({double s=10})=>SizedBox(height:s);
void _snack(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s),duration:const Duration(milliseconds:900)));
}
class _MicroscopePainter extends CustomPainter{final bool grid,compare;_MicroscopePainter({required this.grid,required this.compare});@override void paint(Canvas p,Size s){final center=Offset(s.width/2,s.height/2);final r=s.shortestSide*.36;final paint=Paint()..shader=RadialGradient(colors:[Colors.white.withValues(alpha:.18),Colors.blueGrey.withValues(alpha:.04),Colors.black]).createShader(Rect.fromCircle(center:center,radius:r));p.drawCircle(center,r,paint);p.drawCircle(center,r,Paint()..style=PaintingStyle.stroke..strokeWidth=2..color=Colors.white24);if(compare){p.drawLine(Offset(center.dx,center.dy-r),Offset(center.dx,center.dy+r),Paint()..color=Colors.white38..strokeWidth=1);}}@override bool shouldRepaint(covariant _MicroscopePainter old)=>old.grid!=grid||old.compare!=compare;}
class _GridPainter extends CustomPainter{ @override void paint(Canvas p,Size s){final q=Paint()..color=Colors.white24..strokeWidth=1;for(int i=1;i<4;i++){final x=s.width*i/4;final y=s.height*i/4;p.drawLine(Offset(x,0),Offset(x,s.height),q);p.drawLine(Offset(0,y),Offset(s.width,y),q);}}@override bool shouldRepaint(covariant CustomPainter old)=>false;}

class GalleryScreen extends StatelessWidget{const GalleryScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Fotos salvas (0)')),body:const Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.photo_library_outlined,size:64,color:Colors.white38),SizedBox(height:12),Text('Nenhuma foto nesta prévia',style:TextStyle(color:Colors.white60))]));}
class NotesScreen extends StatelessWidget{const NotesScreen({super.key});@override Widget build(BuildContext c)=>DefaultTabController(length:2,child:Scaffold(appBar:AppBar(title:const Text('Anotações & Tarefas'),bottom:const TabBar(tabs:[Tab(text:'Anotações',icon:Icon(Icons.sticky_note_2_outlined)),Tab(text:'Tarefas',icon:Icon(Icons.checklist_outlined))])),body:const TabBarView(children:[_Empty(text:'Nenhuma anotação'),_Empty(text:'Nenhuma tarefa')]));}
class ControlsScreen extends StatelessWidget{const ControlsScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Controles e configurações')),body:ListView(padding:const EdgeInsets.all(16),children:[const _Section(title:'Câmera',children:[_FakeSlider(label:'Brilho'),_FakeSlider(label:'Contraste'),_FakeSlider(label:'Saturação'),_FakeSlider(label:'Nitidez')]),const SizedBox(height:16),const _Section(title:'Interface',children:[_FakeSwitch(label:'Modo escuro',value:true),_FakeSwitch(label:'Mostrar grade',value:false),_FakeSwitch(label:'Foco central',value:false)]),const SizedBox(height:16),Card(child:ListTile(leading:const Icon(Icons.gesture),title:const Text('Guia de gestos'),subtitle:const Text('Prévia da navegação e atalhos'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const GesturesScreen()))))]));}
class _Section extends StatelessWidget{final String title;final List<Widget> children;const _Section({required this.title,required this.children});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:12),...children])));}
class _FakeSlider extends StatelessWidget{final String label;const _FakeSlider({required this.label});@override Widget build(BuildContext c)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label),Slider(value:.58,onChanged:(_){})]);}
class _FakeSwitch extends StatelessWidget{final String label;final bool value;const _FakeSwitch({required this.label,required this.value});@override Widget build(BuildContext c)=>SwitchListTile(contentPadding:EdgeInsets.zero,title:Text(label),value:value,onChanged:(_){}) ;}
class GesturesScreen extends StatelessWidget{const GesturesScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Guia de gestos')),body:ListView(padding:const EdgeInsets.all(16),children:const [_Gesture(icon:Icons.pan_tool,title:'Arrastar',text:'Navegue pela imagem'),_Gesture(icon:Icons.zoom_in,title:'Pinça',text:'Aproxime ou afaste'),_Gesture(icon:Icons.touch_app,title:'Toque',text:'Selecione ferramentas')]);}}
class _Gesture extends StatelessWidget{final IconData icon;final String title,text;const _Gesture({required this.icon,required this.title,required this.text});@override Widget build(BuildContext c)=>Card(child:ListTile(leading:Icon(icon,size:30),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(text)));}
class _Empty extends StatelessWidget{final String text;const _Empty({required this.text});@override Widget build(BuildContext c)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.inbox_outlined,size:54,color:Colors.white30),const SizedBox(height:10),Text(text,style:const TextStyle(color:Colors.white54))]));}
